# Generated by Django 5.2 on 2025-05-01 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examen', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examen',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='examen',
            name='creado_por',
        ),
        migrations.RemoveField(
            model_name='examen',
            name='curso',
        ),
        migrations.AlterField(
            model_name='examen',
            name='tiempo_limite',
            field=models.IntegerField(help_text='Tiempo en minutos'),
        ),
        migrations.AlterField(
            model_name='examen',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
