# Generated by Django 5.2 on 2025-05-04 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examen', '0002_auto_20240320'),
        ('examen', '0002_remove_examen_categoria_remove_examen_creado_por_and_more'),
    ]

    operations = [
    ]
