# Generated by Django 5.2 on 2025-05-01 00:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Membresia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('monto_total', models.DecimalField(decimal_places=2, default=120.0, max_digits=8)),
                ('plan', models.CharField(choices=[('Plan Anual 1 (Mañana)', 'Plan Anual 1 (Mañana)'), ('Plan Anual 2 (Tarde)', 'Plan Anual 2 (Tarde)'), ('Plan Anual 3 (Mañana)', 'Plan Anual 3 (Mañana)'), ('Plan Anual Virtual (Mañana)', 'Plan Anual Virtual (Mañana)'), ('Plan Escolar 1 (Interdiario Mañana)', 'Plan Escolar 1 (Interdiario Mañana)'), ('Plan Escolar 2 (Interdiario Tarde)', 'Plan Escolar 2 (Interdiario Tarde)'), ('Plan Sabatino 1 (Mañana)', 'Plan Sabatino 1 (Mañana)'), ('Plan Semestral 1 (Mañana)', 'Plan Semestral 1 (Mañana)'), ('Plan Beca 18 (Mañana)', 'Plan Beca 18 (Mañana)')], default='Plan Anual 1 (Mañana)', max_length=40)),
                ('tipo', models.CharField(choices=[('Individual', 'Individual'), ('Duo', 'Duo'), ('Trío', 'Trío')], default='Individual', max_length=20)),
                ('tipo_pago', models.CharField(choices=[('Efectivo', 'Efectivo'), ('Tarjeta', 'Tarjeta'), ('Transferencia', 'Transferencia'), ('Yape', 'Yape'), ('Plin', 'Plin'), ('Otros', 'Otros')], default='Efectivo', max_length=20)),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PagoMembresia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateField(auto_now_add=True)),
                ('monto_pagado', models.DecimalField(decimal_places=2, max_digits=8)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('capacidad', models.IntegerField(default=20)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Salón',
                'verbose_name_plural': 'Salones',
            },
        ),
    ]
