# Generated by Django 5.2 on 2025-05-01 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnlaceClaseGrabada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(blank=True, max_length=500, null=True)),
                ('detalles', models.TextField(blank=True, null=True)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Enlace de Clase Grabada',
                'verbose_name_plural': 'Enlaces de Clases Grabadas',
                'ordering': ['-fecha_subida'],
            },
        ),
        migrations.CreateModel(
            name='EnlaceCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_curso', models.CharField(max_length=200)),
                ('link', models.URLField(blank=True, max_length=500, null=True)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Enlace de Curso',
                'verbose_name_plural': 'Enlaces de Cursos',
                'ordering': ['-fecha_subida'],
            },
        ),
    ]
