# Generated by Django 5.2 on 2025-05-01 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enlaces', '0001_initial'),
        ('membresias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enlaceclasegrabada',
            name='salon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grabaciones', to='membresias.salon'),
        ),
        migrations.AddField(
            model_name='enlacecurso',
            name='salon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos_grabados', to='membresias.salon'),
        ),
    ]
