# Generated by Django 5.2 on 2025-05-01 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportacionNotas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_importacion', models.DateTimeField(auto_now_add=True)),
                ('nombre_archivo', models.CharField(help_text='Nombre del archivo de referencia', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modo', models.CharField(choices=[('presencial', 'Presencial'), ('virtual', 'Virtual')], default='presencial', help_text='Modalidad del examen: presencial o virtual', max_length=20)),
                ('puntaje', models.DecimalField(decimal_places=2, max_digits=7)),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=5)),
                ('correctas', models.IntegerField()),
                ('incorrectas', models.IntegerField()),
                ('no_respuesta', models.IntegerField()),
                ('act', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('hm', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('hv', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('arit', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('geo', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('alge', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('trigo', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('lengua', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('lit', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('psi', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('civ', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('hp', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('hu', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('geo_l', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('eco', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('filo', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('fis', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('qui', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('bio', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
